### ISSUE TITLE
prune down spaghetti description

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal.github.io#178]
The length of `spaghetti`'s description causes the "Visit The Page" button to not be visible on the flip tile.

<img width="770" alt="Screen Shot 2020-12-27 at 8 29 06 PM" src="https://user-images.githubusercontent.com/8590583/103183822-d287de00-4882-11eb-934f-6ac133c0ec03.png">

**Comment by jGaboardi** [comment]
Probably a change like the following will do it:

> Spaghetti supports the spatial analysis of graphs, networks, topology, and inference. It includes a robust all-to-all Dijkstra shortest path algorithm, the ability to connect near-network observations onto the network, functionality for the statistical testing of clusters on networks, and high-performance geometric and spatial computations.

**Comment by knaaptime** [comment]
resolved by #179
