### ISSUE TITLE
Where should news go?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal.github.io#208]
Should news entries go into [`_data/news.yml`](https://github.com/pysal/pysal.github.io/blob/master/_data/news.yml) or [`content/news/*.md`](https://github.com/pysal/pysal.github.io/tree/master/content/news/)? We have been putting them into the latter for several years now and I just want to make sure that is the correct place?

**Comment by ecv19** [comment]
New entries should go under content/news/
