### ISSUE TITLE
update submodule contract

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal.github.io#49]
the submodule contracts have diverged between the site & the wiki. 

we need to:

1. update the site's [submodule contract from the wiki](https://github.com/pysal/pysal/wiki/Submodule-Contract) 
2. delete the submodule contract in the wiki
3. update any links to submodule contract coming in from elsewhere (maybe the migrating directions?)

**Comment by weikang9009** [comment]
1. The site has been updated http://pysal.org/getting_started.html#submodule-contract
2. I am going to delete the submodule contract wiki and further editing of the contract should be made in the site
3. The links to submodule contract in migrating directions is updated in https://github.com/pysal/pysal.github.io/pull/57
