### ISSUE TITLE
instructions on how to work with the website

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal.github.io#51]
For new users:

1. `git clone --recurse-submodules git@github.com:pysal/pysal.site`
    this grabs the current copy of *both* the build scripts (which are in `pysal/pysal.site`), and the current user-facing website (which is in `pysal/pysal.github.io`). For git purposes, think of this like two independent repos. The first, `pysal.site`, stores all the stuff we used to build the website, plus a snapshot of the website (in `build/html`). The second, `pysal.github.io`, lives within `build/html`, and is tracked independently. There's a remote (called `origin` by default) for both, and both refer to `pysal`'s copy.
2. Each individual who wants to work on the site needs to add *their fork* of the public-facing website and the private-facing build stuff. To do this:
     1. `cd pysal.site/build/html` changes the working directory to the public-facing website. 
     2. pick a good, memorable name for your personal copy. I often call mine `wolf`. Then, `git remote add wolf git@github.com:ljwolf/pysal.github.io`. This adds my fork to the public-facing site and calls it `wolf`. 
    3. go back to the git root: `cd ../../` and make sure you're in `pysal.site`
    4. Then, to add your fork of the *private* building area, use `git remote add wolf git@github.com:ljwolf/pysal.site`.

Now, your repository has the two modules, the "root" module `pysal.site`, which is the private building area, and the "submodule", stored in `build/html`, which refers to `pysal.github.io` and which only contains static html files. 

Every time you run `make html`, this dumps into the *public* submodule, `build/html`, which is linked to https://github.com/pysal/pysal.github.io. 
Changes to `build/html` can be added *from inside* and pushed to `pysal.github.io`. 
But, `pysal.site` only records the *commit* referring to changes in `pysal.github,.io`.

**Comment by weikang9009** [comment]
1. ```cd pysal.site/```
2. ```make html```
3. ```cd build/html```
4. You need to add a new remote like this `git remote add sjsrey git@github.com:sjsrey/pysal.github.io`
5. commit all the changes insidel build/html/ `git add .`  , 'git commit`
6. push the local changes to your remote copy `git push sjsrey master`
7. create a pr

**Comment by sjsrey** [comment]
I am unable to get this working. I've tried several different clean installs and deleted my forks, etc. No joy:

Following @weikang9009 steps 1-8, and changing the index.rst file to update a link I get:

```
(libpysal) build/html - [1ab2106...●] » git add .
(libpysal) build/html - [1ab2106...●] » git commit -m 'doc: update inequality links'
[detached HEAD 156ec7a] doc: update inequality links
 20 files changed, 394 insertions(+), 387 deletions(-)
 rewrite _static/documentation_options.js (97%)
 rewrite searchindex.js (99%)
(libpysal) build/html - [156ec7a...] » git push sjsrey master
Everything up-to-date
```

I reckon the detached HEAD is the problem, but I've hit this a couple of times trying to start over. So either I'm missing/kludging something with @ljwolf instructions or @weikang9009 instructions.

**Comment by ljwolf** [comment]
Did you make after changing the rst?

**Comment by sjsrey** [comment]
Yup on make after changing

**Comment by ljwolf** [comment]
Hmm. Not sure... Will try to replicate on a clean head.

**Comment by weikang9009** [comment]
@sjsrey I think the steps you followed are correct. Not sure about the issue though. Can you try `git pull origin master` before your last step -`git push sjsrey master` ?

**Comment by sjsrey** [comment]
after `git pull origin master`

```
(libpysal) build/html - [71732ec...] » git pull origin master
From https://github.com/pysal/pysal.github.io
 * branch            master     -> FETCH_HEAD
Auto-merging team.html
CONFLICT (content): Merge conflict in team.html
Auto-merging searchindex.js
CONFLICT (content): Merge conflict in searchindex.js
Auto-merging search.html
CONFLICT (content): Merge conflict in search.html
Auto-merging news.html
CONFLICT (content): Merge conflict in news.html
Auto-merging install.html
CONFLICT (content): Merge conflict in install.html
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
Auto-merging getting_started.html
CONFLICT (content): Merge conflict in getting_started.html
Auto-merging genindex.html
CONFLICT (content): Merge conflict in genindex.html
Auto-merging gallery.html
CONFLICT (content): Merge conflict in gallery.html
Auto-merging docs.html
CONFLICT (content): Merge conflict in docs.html
Auto-merging contact.html
CONFLICT (content): Merge conflict in contact.html
Auto-merging about.html
CONFLICT (content): Merge conflict in about.html
Auto-merging _static/basic.css
Auto-merging .buildinfo
CONFLICT (content): Merge conflict in .buildinfo
Automatic merge failed; fix conflicts and then commit the result.
(libpysal) build/html - [71732ecf54318c635b886fdfee8183ed74747d81●●|merge] »
```

**Comment by weikang9009** [comment]
Just submit a commit to pysal/pysal.site to sync pysal/pysal.site with pysal/pysal.github.io 

Try `git pull upstream master` from  pysal/pysal.site and then try `git pull origin master` from pysal/pysal.github.io within `build/html`?

**Comment by sjsrey** [comment]
Still conflicts.

**Comment by sjsrey** [comment]
I have it working now. But don't know what has changed.

**Comment by sjsrey** [comment]
Can we refactor this to a more transparent approach? I'm on my second weekend of trying to make a simple change to the pysal.org site with this submodule approach and am spending painful time debugging. I started over from scratch following the directions in this thread and am not successful. I think the submodule is causing more trouble than it is worth.

**Comment by sjsrey** [comment]
This is still pretty painful and is causing a lot of friction (at least for me)  in attempting to post  updates. I am hitting the same "unpopulated submodule" error. After an hour of edits and attempts at debugging, I'm afraid I'm giving up in trying to announce the 2.0 release on the site.

Pinging @ljwolf or @weikang9009 to help with posts isn't really scalable and I hope we can move to a more transparent update model.

**Comment by jGaboardi** [comment]
Since we change website build structure (#90), this issue can can be close, correct?
