### ISSUE TITLE
Not trigger rebuild?

### ISSUE THREAD

**Issue by weikang9009** [pysal/pysal.github.io#56]
It seems that the website is not updated with changes to this repo. Any idea how to configure it?

**Comment by ljwolf** [comment]
This is an issue with getting the A records set up. @sjsrey moved domain registrars, but the A name stuff hasn't been activated yet. Not sure why, but I don't think any of us can do that without access to the `pysal.org` domain registry console.

**Comment by ljwolf** [comment]
Fwiw, I think using the ANAME/ALIAS is preferred to setting A records individually, and I think it's faster to set up?

https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by sjsrey** [comment]
Unfortunately hover doesn't support ANAME/ALIAS. I've just reset things hoping that the previous settings were off. Here is what we have (says it could take up to 15 mintues to kick in)
![2018-07-22-1710-1532304653-sel](https://user-images.githubusercontent.com/118042/43051701-5b9be47a-8dd2-11e8-9d23-81e3b14b3bde.png)

**Comment by sjsrey** [comment]
On further inspection,  I don't think the transfer from bluehost to hover has kicked in yet:

```
~ » ping pysal.org
PING pysal.org (162.241.219.38) 56(84) bytes of data.
64 bytes from box5613.bluehost.com (162.241.219.38): icmp_seq=1 ttl=46 time=39.9 ms
```

The instructions said it could take up to 5-7 business days for this to kick in.

```

8. How long does a domain transfer take?

There are many factors that will affect the time it takes for your domain to transfer, so it is difficult to provide an accurate estimate. Things like your current registrar’s policies and support, as well as the domain’s extension/top-level domain, can all affect the length of the transfer. Be prepared for the process to wait 1-2 weeks to finalize.
```
[Source](https://help.hover.com/hc/en-us/articles/217281757-How-to-Transfer-my-domain-to-Hover-Domain-Transfer-FAQ)

**Comment by sjsrey** [comment]
A little more digging reveals that because we had the subdomain `migrating.pysal.org` parked on bluehost, the move of pysal.org was not going through. I had to delete the subdomain, and now I think the transfer of `pysal.org` works.

The side-effect is that `migraine.pysal.org`[ is broken now ](https://github.com/pysal/pysal.site/issues/10).

**Comment by weikang9009** [comment]
Just checked the pysal.org, it has been successfully updated to reflect the newest content in the github page repo. Thanks!

All the contents of the migrating page have been included in http://pysal.org/about.html#migrating-to-pysal-2-0 We can update links to point here
