### ISSUE TITLE
core developers

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal.github.io#93]
Our [About](http://pysal.org/about) section includes mostly folks who are currently active developers, but also includes folks who are not currently active. Also, people who have made significant contributions in the past are not included. I propose we have two sections. Something simple like "Current Core Developers" and "Past Core Developers" would alleviate this discrepancy. Thoughts?

**Comment by knaaptime** [comment]
maybe Contributors if they're no longer active?

**Comment by jGaboardi** [comment]
@knaaptime I am listed as a [contributor to shapely](https://github.com/Toblerity/Shapely/blob/master/CREDITS.txt) due to my [incredibly small PR](https://github.com/Toblerity/Shapely/pull/655). I feel like listing former pysal members as mere contributors undercuts their efforts (or maybe I'm thinking too much?).

**Comment by weikang9009** [comment]
I like the idea of "Current" and "Past", but I would vote for including all of them under the same title "Core Developers".

**Comment by sjsrey** [comment]
> I like the idea of "Current" and "Past", but I would vote for including all of them under the same title "Core Developers".

I can take this on and will un-assign everybody except me so as to not duplicate efforts. If others want to join in, just ad yourself back on through assignment.

**Comment by jGaboardi** [comment]
Being addressed in #95.
