### ISSUE TITLE
Where did the submodule contract go?

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal.github.io#96]
We used to have recorded the list of guidelines needed for subpackages to get distributed in the old website. We called this the "submodule contract," mimicking the sklearn contract.

We should probably put this into our contributing documentation. This would require 

- finding it in the old website source
- moving it into the wiki

**Comment by jGaboardi** [comment]
This was also brought to our attention in the [May 2019 developer meeting](https://hackmd.io/AwCIXkG8RoW4anRLruoFNA?both).

@sjsrey @weikang9009
