### ISSUE TITLE
sptaital error model incorrectly described

### ISSUE THREAD

**Issue by StevenLi-DS** [pysal/pysal.github.io#98]
Shouldn't this [function](https://pysal.readthedocs.io/en/latest/generated/pysal.model.spreg.ML_Error.html#pysal.model.spreg.ML_Error) be described as the spatial error model?

![image](https://user-images.githubusercontent.com/33796896/57106743-2e8c0f00-6cfc-11e9-9f97-2b962dd5665e.png)

**Comment by darribas** [comment]
Thanks very much for reporting! This should be fixed over at [`spreg`](https://github.com/pysal/spreg)

**Comment by jGaboardi** [comment]
pysal/spreg#20

**Comment by weikang9009** [comment]
addressed via https://github.com/pysal/spreg/pull/24
